apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE ecommerce_orders;
    CREATE DATABASE ecommerce_users;
