{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ include "ecommerce.postgresPassword" . | quote }}
  database-url-orders: {{ printf "postgresql+asyncpg://%s:%s@postgres:5432/ecommerce_orders" .Values.postgres.auth.username (include "ecommerce.postgresPassword" .) | quote }}
  database-url-users: {{ printf "postgresql+asyncpg://%s:%s@postgres:5432/ecommerce_users" .Values.postgres.auth.username (include "ecommerce.postgresPassword" .) | quote }}
{{- end }}
