apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  postgres-password: postgres
  database-url-orders: postgresql+asyncpg://postgres:postgres@postgres:5432/ecommerce_orders
  database-url-users: postgresql+asyncpg://postgres:postgres@postgres:5432/ecommerce_users
