server {
    listen 80;
    server_name localhost;

    # Статика React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Прокси к Product Service (Go)
    location /api/products {
        proxy_pass http://product-service:8080;
        proxy_set_header Host $host;
    }

    # Прокси к Order Service (Python) — FastAPI требует trailing slash
    location /api/orders {
        proxy_pass http://order-service:8000/api/orders/;
        proxy_set_header Host $host;
    }

    # Прокси к User Service (Python) — FastAPI требует trailing slash
    location /api/users {
        proxy_pass http://user-service:8000/api/users/;
        proxy_set_header Host $host;
    }
}
