apiVersion: v2
name: ecommerce
description: E-commerce microservices platform — frontend, product/order/user services, PostgreSQL
type: application
version: 0.2.0
appVersion: "1.0"
keywords:
  - ecommerce
  - microservices
  - kubernetes
maintainers:
  - name: Konstantin Tokarenko
    url: https://github.com/TokarenkoKonstantin
